language: node_js
script:
- npm run precommit
before_deploy:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: hU/fS0ZzuSfehJSU1/CLA46yiLzNADvOIC6GKjEIh6k6JRhXRq9lXwezYlcQnopOQORbElCXiTamsTUEdvof2oxHjC+yVCZQTtHvZ/Gibb3OT3Z+zwjNd7IjWtj5AQ4x8JkQdFIF7pmzk2XO9j3L8WqaJQihAv9Mb6ceV6Xw28jvjY5yQElLhNAYR+A+11TYj5yBmmYUWMR5VEehwzyZtLzTuhxrlwpfGyuT2RRNnmkfOsqQOSHIFzUVFZbi4d/c3TsD8aC5PdxPhPc/3UV8yxWeOtKDsmKzNEPbwh+3IplErD0fnsxb9ixbLFxTG7reb7rPG1flmb+7NyqEjp8+we4vSgK1xH/Px3rRxeUz6Ti4NEgDg8krWbgS4TJD4cF5dl+K7gmOesRgcVA3AnuJhFbiM3zc7kEan6UppEGumD1kECJLDUAx24kTYS5pokhZtcP2frzjFy9R6s1zCBV7yZPzf36FVaGqpz2pVCEHIbWLs+hqHWRbp7Da6jWKnPIzVoVu4WZCXLF4T764LrRI+rNj+9Ii03vFzXhJ/IsVx87J/NIlj33rcUbkQzb7IbPmrCsWctZrarerF2GelioV2tyP7OSZaWgsLIozUWB5jTbuAOfefcl91gARsXnlLN9LkG/KVanCAq9UevFjXqnuHECo/IOsu3nSxZA9GseJo80=
  app: MelbBuild2017S2_Dragons
  on:
    repo: twlevelup/MelbBuild2017S2_Dragons
