import React from 'react';
import Date from '../../../framework/components/Date/Date';
import Time from '../../../framework/components/Time/Time';
import ButtonAction from '../../../framework/util/ButtonAction';
import WithButtonConfigs from '../../../framework/containers/WithButtonConfigs';
import './HomeScreen.css';

import dragonSpinner from './dragon-spinner.gif';


export const HomeScreenComponent = () => {
  return (
    <div id='watch-home-page'>
      <Date />
      <Time />
      <div id='home-page-content'>
        <img id='dragon_img' src={ dragonSpinner } alt='dragon-spinner' />
        <br />
        <br />
        <br />
        <h3>The Myth of The Dragon<br />Dragons of Africa<br />**Aido Hwedo**</h3>

        <h4>Physical Description</h4>
        <p>Aido Hwedo was a giant python or an enormous python-like serpent
        with vast coils. Sometimes he was described as being celestial blue.
        Other accounts claimed that he had yellow and red stripes that ran the
        length of his body or that he was brilliantly multicolored.
        Aido Hwedo, to this day, can be seen in the sky as a rainbow, or in the
        light reflected off water.</p>

        <h4>About Aido Hwedo</h4>
        <p>Aido Hwedo was the Rainbow Serpent and the great cosmic serpent in
          Dahomey and Fon mythology. He was sometimes called the great python,
          for he served Mawu&ndash;Lisa during the creation of the world.
          Though some accounts maintained that Mawu&ndash;Lisa created the
          Rainbow Serpent first, before anything else in the universe, others
          claimed that Aido Hwedo came into being with the first human beings
          or that he existed even before Mawu&ndash;Lisa. Thus, he was not
          considered the son of the supreme deity.

          Aido Hwedo was so enormous that he had to eat vast quantities of
          iron to sustain his strength. When there was not enough iron, he
          would devour his own tail to sustain himself.
          He served Mawu&ndash;Lisa and participated in the creation of the universe
          by acting as Mawu&ndash;Lisa&#39;s vehicle as she filled the world,
          transporting her through the cosmos by carrying her in his mouth.
          He supported the earth by curling underneath it to ensure that
          everything in the universe remained in its place. To this day, Aido
          Hwedo continues in this task.

          Later, the great Rainbow Serpent became known for his jealous nature,
          and believers were careful not to incur his wrath. Newlyweds
          presented special offerings to Aido Hwedo, and relatives petitioned
          him not to harm them.
        </p>

        <h4>Aido Hwedo in the Creation of the World</h4>
        <p>Mawu&ndash;Lisa created humans on the first day, and thereafter made
          everything else with the help of Aido Hwedo, who carried the deity
          in his mouth. That is why the world is shaped the way it is. There
          are winding curves and both high and low places; all of these were
          made by the movements of the Rainbow Serpent.

          His tracks became chasms, sloping curves, and the rivers. Each night,
          Mawu&ndash;Lisa and Aido Hwedo would rest, and the serpent would leave vast
          piles of excrement, which built up the mountains and filled them
          with minable treasures and other riches.</p>

        <h4>Aido Hwedo as the World Serpent</h4>
        <p>When Mawu&ndash;Lisa finished, she became worried that the world might sink
          under the weight of itself, because there were too many things on its
          surface: too many mountains, too many trees, too many big animals,
          and so on. When she realized its great weight would continue to
          increase, she feared it would fall through the cosmos. Thus, it was
          necessary to rest the world on something that could support its
          incredible weight to prevent it from toppling.
          Thus, the supreme deity decreed that Aido Hwedo could support the
          world on his coiled body. She asked the Rainbow Serpent to circle
          himself under the earth and hold it in place by gripping his tail in
          his mouth. Thereafter, whenever he shifted, the earth moved, either
          as a tremor or an earthquake.
          While his body held up the world, the heat generated by his efforts
          put him in agony, so Mawu&ndash;Lisa crafted the seas and the oceans to
          keep Aido Hwedo cool. The Rainbow Serpent despised heat, so he
          remained submerged in the waters of the sea to keep comfortable.

          Unfortunately, sometimes the oceans were not enough to keep Aido
          Hwedo properly cool, and he writhes in pain. These snake&ndash;like
          stirrings caused violent earthquakes from time to time.</p>

        <h4>Aido Hwedo and the End of the World</h4>
        <p>Since Aido Hwedo coiled under the earth, he could no longer acquire new
        food sources. ccording to some traditions, there were red monkeys that
        lived in the sea, and they created iron bars to feed Aido Hwedo. Other
        traditions maintain that Aido Hwedo had an enormous supply of iron
        under the earth that was gradually diminishing. However, should the
        monkeys fail to produce enough food, or when the iron supply was gone,
        Aido Hwedo would be forced to eat his own tail. Once that was gone,
        the whole world would end by falling completely into the oceans.</p>

        <h4>Quick Facts</h4>
        <ul>
          <li>Aido Hwedo was the Rainbow Serpent and the great cosmic serpent in
        Dahomey and Fon mythology.</li>
          <li>He carried the Mawu&ndash;Lisa in his mouth while she created the
          world.</li>
          <li>He was so enormous that he had to eat vast quantities of iron to
          sustain his strength.</li>
          <li>Aido Hwedo was a giant python or an enormous python&ndash;like serpent
          with vast coils.</li>
          <li>His tracks became chasms, sloping curves, and the rivers.</li>
          <li>Aido Hwedo supported the world on his coiled body.</li>
          <li>Mawu&ndash;Lisa crafted the seas and the oceans to keep Aido Hwedo
          cool.</li>
          <li>When he writhes or moves, the earth quakes.</li>
          <li>Once he consumes all the iron under the earth, he will be forced
          to eat his own tail, and when that is gone, the world will end 0 by
          falling into the oceans.</li>
        </ul>

        <p>Source: http://www.blackdrago.com/fame/aidohwedo.htm</p>
      </div>
    </div>
  );
};

export const HomeScreenButtons = {
  LEFT: () => ButtonAction.goToPage({ pathname: '/counter', state: { number: 0 } }),
  RIGHT: () => ButtonAction.goToPage('/welcome'),
  TOP: () => ButtonAction.scrollUp(),
  BOTTOM: () => ButtonAction.scrollDown(),
};

export default WithButtonConfigs(HomeScreenComponent, HomeScreenButtons);
